services:
  server:
    # image: server_image
    # container_name: server_container
    platform: linux/amd64
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
  client:
    # To keep the container running
    # image: client_image
    # container_name: client_container
    platform: linux/amd64
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
