docker exec lightblocks-client-1 /app/bin/client --username nir1 --msgs '[
    { "action": "addItem", "key": "1", "value": "nir1" },
    { "action": "addItem", "key": "2", "value": "nir1" },
    { "action": "addItem", "key": "3", "value": "nir1" },
    { "action": "addItem", "key": "4", "value": "nir1" },
    { "action": "getItem", "key": "1"},
    { "action": "addItem", "key": "6", "value": "nir1" },
    { "action": "addItem", "key": "7", "value": "nir1" },
    { "action": "addItem", "key": "8", "value": "nir1" },
    { "action": "addItem", "key": "9", "value": "nir1" },
    { "action": "addItem", "key": "10", "value": "nir1" },
    { "action": "deleteItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "addItem", "key": "11", "value": "nir1" },
    { "action": "addItem", "key": "12", "value": "nir1" },
    { "action": "getItem", "key": "2", "value": "nir1" },
    { "action": "getItem", "key": "4", "value": "nir1" },
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "6", "value": "nir1" },
    { "action": "getItem", "key": "5", "value": "nir1" },
    { "action": "getItem", "key": "7", "value": "nir1" },
    { "action": "getItem", "key": "2", "value": "nir1" },
    { "action": "getItem", "key": "1", "value": "nir1" },
    { "action": "addItem", "key": "1", "value": "nir1" },
    { "action": "addItem", "key": "21", "value": "nir1" },
    { "action": "addItem", "key": "22", "value": "nir1" },
    { "action": "addItem", "key": "23", "value": "nir1" },
    { "action": "addItem", "key": "24", "value": "nir1" },
    { "action": "addItem", "key": "25", "value": "nir1" },
    { "action": "addItem", "key": "26", "value": "nir1" },
    { "action": "addItem", "key": "27", "value": "nir1" },
    { "action": "addItem", "key": "28", "value": "nir1" },
    { "action": "addItem", "key": "29", "value": "nir1" },
    { "action": "addItem", "key": "30", "value": "nir1" },
    { "action": "addItem", "key": "31", "value": "nir1" },
    { "action": "addItem", "key": "32", "value": "nir1" },
    { "action": "addItem", "key": "33", "value": "nir1" },
    { "action": "addItem", "key": "34", "value": "nir1" },
    { "action": "addItem", "key": "35", "value": "nir1" },
    { "action": "addItem", "key": "36", "value": "nir1" },
    { "action": "addItem", "key": "37", "value": "nir1" },
    { "action": "addItem", "key": "38", "value": "nir1" },
    { "action": "addItem", "key": "39", "value": "nir1" },
    { "action": "addItem", "key": "40", "value": "nir1" },
    { "action": "addItem", "key": "41", "value": "nir1" },
    { "action": "addItem", "key": "42", "value": "nir1" },
    { "action": "addItem", "key": "43", "value": "nir1" },
    { "action": "addItem", "key": "44", "value": "nir1" },
    { "action": "addItem", "key": "45", "value": "nir1" },
    { "action": "addItem", "key": "46", "value": "nir1" },
    { "action": "addItem", "key": "47", "value": "nir1" },
    { "action": "addItem", "key": "48", "value": "nir1" },
    { "action": "addItem", "key": "49", "value": "nir1" },
    { "action": "addItem", "key": "50", "value": "nir1" },
    { "action": "addItem", "key": "51", "value": "nir1" },
    { "action": "addItem", "key": "52", "value": "nir1" },
    { "action": "addItem", "key": "53", "value": "nir1" },
    { "action": "addItem", "key": "54", "value": "nir1" },
    { "action": "addItem", "key": "55", "value": "nir1" },
    { "action": "addItem", "key": "56", "value": "nir1" },
    { "action": "addItem", "key": "57", "value": "nir1" },
    { "action": "addItem", "key": "58", "value": "nir1" },
    { "action": "addItem", "key": "59", "value": "nir1" },
    { "action": "addItem", "key": "60", "value": "nir1" },
    { "action": "addItem", "key": "61", "value": "nir1" },
    { "action": "addItem", "key": "62", "value": "nir1" },
    { "action": "addItem", "key": "63", "value": "nir1" },
    { "action": "addItem", "key": "64", "value": "nir1" },
    { "action": "addItem", "key": "65", "value": "nir1" },
    { "action": "addItem", "key": "66", "value": "nir1" },
    { "action": "addItem", "key": "67", "value": "nir1" },
    { "action": "addItem", "key": "68", "value": "nir1" },
    { "action": "addItem", "key": "69", "value": "nir1" },
    { "action": "addItem", "key": "70", "value": "nir1" },
    { "action": "addItem", "key": "71", "value": "nir1" },
    { "action": "addItem", "key": "72", "value": "nir1" },
    { "action": "addItem", "key": "73", "value": "nir1" }]'

    docker exec lightblocks-client-1 /app/bin/client --username nir1 --msgs '[
     { "action": "addItem", "key": "21", "value": "nir1" },
    { "action": "addItem", "key": "22", "value": "nir1" },
    { "action": "addItem", "key": "23", "value": "nir1" },
    { "action": "addItem", "key": "24", "value": "nir1" },
    { "action": "addItem", "key": "25", "value": "nir1" },
    { "action": "addItem", "key": "26", "value": "nir1" },
    { "action": "addItem", "key": "27", "value": "nir1" },
    { "action": "addItem", "key": "28", "value": "nir1" },
    { "action": "addItem", "key": "29", "value": "nir1" },
    { "action": "addItem", "key": "30", "value": "nir1" },
    { "action": "addItem", "key": "31", "value": "nir1" },
    { "action": "addItem", "key": "32", "value": "nir1" },
    { "action": "addItem", "key": "33", "value": "nir1" },
    { "action": "addItem", "key": "34", "value": "nir1" },
    { "action": "addItem", "key": "35", "value": "nir1" },
    { "action": "addItem", "key": "36", "value": "nir1" },
    { "action": "addItem", "key": "37", "value": "nir1" },
    { "action": "addItem", "key": "38", "value": "nir1" },
    { "action": "addItem", "key": "39", "value": "nir1" },
    { "action": "addItem", "key": "40", "value": "nir1" },
    { "action": "addItem", "key": "41", "value": "nir1" },
    { "action": "addItem", "key": "42", "value": "nir1" },
    { "action": "addItem", "key": "43", "value": "nir1" },
    { "action": "addItem", "key": "44", "value": "nir1" },
    { "action": "addItem", "key": "45", "value": "nir1" },
    { "action": "addItem", "key": "46", "value": "nir1" },
    { "action": "addItem", "key": "47", "value": "nir1" },
    { "action": "addItem", "key": "48", "value": "nir1" },
    { "action": "addItem", "key": "49", "value": "nir1" },
    { "action": "addItem", "key": "50", "value": "nir1" },
    { "action": "addItem", "key": "51", "value": "nir1" },
    { "action": "addItem", "key": "52", "value": "nir1" },
    { "action": "addItem", "key": "53", "value": "nir1" },
    { "action": "addItem", "key": "54", "value": "nir1" },
    { "action": "addItem", "key": "55", "value": "nir1" },
    { "action": "addItem", "key": "56", "value": "nir1" },
    { "action": "addItem", "key": "57", "value": "nir1" },
    { "action": "addItem", "key": "58", "value": "nir1" },
    { "action": "addItem", "key": "59", "value": "nir1" },
    { "action": "addItem", "key": "60", "value": "nir1" },
    { "action": "addItem", "key": "61", "value": "nir1" },
    { "action": "addItem", "key": "62", "value": "nir1" },
    { "action": "addItem", "key": "63", "value": "nir1" },
    { "action": "addItem", "key": "64", "value": "nir1" },
    { "action": "addItem", "key": "65", "value": "nir1" },
    { "action": "addItem", "key": "66", "value": "nir1" },
    { "action": "addItem", "key": "67", "value": "nir1" },
    { "action": "addItem", "key": "68", "value": "nir1" },
    { "action": "addItem", "key": "69", "value": "nir1" },
    { "action": "addItem", "key": "70", "value": "nir1" },
    { "action": "addItem", "key": "71", "value": "nir1" },
    { "action": "addItem", "key": "72", "value": "nir1" },
    { "action": "addItem", "key": "73", "value": "nir1" },
    { "action": "addItem", "key": "74", "value": "nir1" },
    { "action": "addItem", "key": "75", "value": "nir1" },
    { "action": "addItem", "key": "76", "value": "nir1" },
    { "action": "addItem", "key": "77", "value": "nir1" },
    { "action": "addItem", "key": "78", "value": "nir1" },
    { "action": "addItem", "key": "79", "value": "nir1" },
    { "action": "addItem", "key": "80", "value": "nir1" },
    { "action": "addItem", "key": "81", "value": "nir1" },
    { "action": "addItem", "key": "82", "value": "nir1" },
    { "action": "addItem", "key": "83", "value": "nir1" },
    { "action": "addItem", "key": "84", "value": "nir1" },
    { "action": "addItem", "key": "85", "value": "nir1" },
    { "action": "addItem", "key": "86", "value": "nir1" },
    { "action": "addItem", "key": "87", "value": "nir1" },
    { "action": "addItem", "key": "88", "value": "nir1" },
    { "action": "addItem", "key": "89", "value": "nir1" },
    { "action": "addItem", "key": "90", "value": "nir1" },
    { "action": "addItem", "key": "91", "value": "nir1" },
    { "action": "addItem", "key": "92", "value": "nir1" },
    { "action": "addItem", "key": "93", "value": "nir1" },
    { "action": "addItem", "key": "94", "value": "nir1" },
    { "action": "addItem", "key": "95", "value": "nir1" },
    { "action": "addItem", "key": "96", "value": "nir1" },
    { "action": "addItem", "key": "97", "value": "nir1" },
    { "action": "addItem", "key": "98", "value": "nir1" },
    { "action": "addItem", "key": "99", "value": "nir1" },
    { "action": "addItem", "key": "100", "value": "nir1" }
]'


    docker exec lightblocks-client-1 /app/bin/client --username nir1 --msgs '[
    { "action": "addItem", "key": "1", "value": "nir1" },
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "addItem", "key": "2", "value": "nir112" },
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "deleteItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "1"},
    { "action": "deleteItem", "key": "1"},
    { "action": "getItem", "key": "1"}]'



   
    docker exec lightblocks-client-1 /app/bin/client --username nir1 --msgs "[
    { "action": "deleteItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "addItem", "key": "1", "value": "nir1" }]"


        docker exec lightblocks-client-1 /app/bin/client --username nir1 --msgs '[
    { "action": "addItem", "key": "1","value": "nir1" },
    { "action": "addItem", "key": "2","value": "nir1" },
    { "action": "addItem", "key": "3","value": "nir1" },
    { "action": "addItem", "key": "4","value": "nir1" },
    { "action": "addItem", "key": "5","value": "nir1" },
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "3"},
    { "action": "getItem", "key": "4"},
    { "action": "getItem", "key": "5"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "3"},
    { "action": "getItem", "key": "4"},
    { "action": "getItem", "key": "5"},
    { "action": "deleteItem", "key": "1"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "3"},
    { "action": "getItem", "key": "4"},
    { "action": "getItem", "key": "5"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "3"},
    { "action": "getItem", "key": "4"},
    { "action": "getItem", "key": "5"},
    { "action": "getItem", "key": "1"},
    { "action": "getItem", "key": "2"},
    { "action": "getItem", "key": "3"},
    { "action": "getItem", "key": "4"},
    { "action": "getItem", "key": "5"}]'